version: '3'
services: 
    react-web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000" 
        tty: true
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev 
        tty: true
        volumes: 
            - /app/node_modules
            - .:/app
        # override a command    
        command: ["npm", "run", "test"]

